name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # This uses the secret you just added to GitHub
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          # Points to the config file you created in Step 2
          config-file: release-please-config.json
          # Points to the manifest file you created in Step 2
          manifest-file: .release-please-manifest.json